export const columns_for_groupping = [
  'marsh_count_prev',
  'marsh_count',
  'train_count_prev',
  'train_count',
  'train_count_diff',
  'train_count_with_otcep_prev',
  'train_count_with_otcep',
  'train_count_with_otcep_diff',
  'vag_count_ot_prev',
  'vag_count_ot',
  'vag_count_ot_diff',
  'vag_count_prev',
  'vag_count',
  'vag_count_diff',
  'core_count_ot_prev',
  'core_count_ot',
  'core_count_ot_diff',
  'vag_per_count_prev',
  'vag_per_count',
  'vag_per_count_diff',
  'vag_count_with_otcep_prev',
  'vag_count_with_otcep',
  'vag_count_with_otcep_diff',
  'core_ves_ot_prev',
  // 'core_ves_ot',
  'core_ves_ot_diff',
  'way_len',
  'e_pf',
  'e_m',
  'e_fact_prev',
  'e_fact',
  'e_fact_diff',
  'de_fact_prev',
  'de_fact',

  'unit',
  'last_vag_count',

  'etran_vag_count',
  'inv_count',
  'etran_price',

  'weight_gr',
  'tara',
  'weight',
  'len'
]
